# Generated by Django 4.2.16 on 2024-09-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=255)),
                ('address_number', models.CharField(max_length=10)),
                ('neighborhood', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('whatsapp', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
